language: go

go:
  - 1.14.5

addons:
  apt:
    packages:
      - sshpass

cache:
  directories:
    - $HOME/.cache/go-build        # Cache the binaries
    - $HOME/gopath/pkg/mod         # Cache the Go modules

install:
  - ssh-keyscan ${gluten_ip} >> ~/.ssh/known_hosts

script:
  - go build
  - sshpass -p ${gluten_pwd} ssh -o StrictHostKeyChecking=no root@${gluten_ip}  'cd gluten && rm -rf gluten-api'
  - sshpass -p ${gluten_pwd} ssh -o StrictHostKeyChecking=no root@${gluten_ip}  'git clone https://github.com/GreenHatHG/gluten-api.git'
  - scp ./gluten root@${gluten_ip}:/root/gluten/gluten-api
  - sshpass -p ${gluten_pwd} ssh -o StrictHostKeyChecking=no root@${gluten_ip}  'systemctl restart gluten'

branches:
  only:
    - master

notifications:
  email: true